run:
  timeout: 10m
  skip-dirs:
    - vendor$
    - third_party$
    - hack
  tests: true
  skip-dirs-use-default: false
linters:
  enable-all: false
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - typecheck
    - varcheck
    - stylecheck
    - staticcheck
    - tagliatelle
  disable:
    - unused
    - deadcode
