name: E2E Test

on:
  push:
    branches:
      - master
    tags:
      - v*
  workflow_dispatch: {}
  pull_request:
    branches:
      - master

env:
  # Common versions
  GO_VERSION: '1.17'

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Setup Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"

      - name: Setup Kind Cluster
        run: |
          kind delete cluster
          kind create cluster --image kindest/node:${{ matrix.k8s-version }}
          kubectl version
          kubectl cluster-info

      - name: Go Build
        run: make build

