name: E2E Test

on:
  push:
    branches:
      - master
    tags:
      - v*
  workflow_dispatch: {}
  pull_request:
    branches:
      - master

env:
  # Common versions
  GO_VERSION: '1.17'

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          make quick_build

      - name: Setup Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
          image: "kindest/node:v1.22.7"
          name: "1st-kind"

      - name: Setup 2nd Kind
        run: |
          kind create cluster --image kindest/node:v1.20.7 --name 2nd-kind --kubeconfig 2nd-kind
          kind get clusters

      - name: Setup 3rd Kind
        run: |
          kind create cluster --image kindest/node:v1.18.20 --name 3rd-kind --kubeconfig 3rd-kind
          kind get clusters

      - name: E2E Test
        run: |
          bin/kubecm version
          echo "Running kubecm add..."
          bin/kubecm add -f 2nd-kind -c
          bin/kubecm add -f 3rd-kind -c
          
#          echo "Running kubecm merge..."
#          bin/kubecm merge -f .
          
          echo "Running kubecm ls..."
          bin/kubecm list
               
          echo "Running kubecm global flag --config..."
          bin/kubecm list --config 2nd-kind
          
          echo "Running kubecm switch..."
          bin/kubecm s 2nd-kind
          
          echo "Running kubecm delete..."
          bin/kubecm d 1st-kind
