name: E2E Test

on:
  push:
    branches:
      - master
    tags:
      - v*
  workflow_dispatch: {}
  pull_request:
    branches:
      - master

env:
  # Common versions
  GO_VERSION: '1.17'

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Setup Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"

      - name: Setup 2nd Kind
        run: |
          kind create cluster --image kindest/node:v1.22.7 --name 2nd-kind --kubeconfig 2nd-kind
          ls
          kubectl version
          kubectl cluster-info

      - name: Check Kind Cluster
        run: |
          kubectl version
          kubectl cluster-info

      - name: Go Build
        run: make quick_build

      - name: E2E Test
        run: |
          bin/kubecm version
          bin/kubecm add -f 2nd-kind
          bin/kubecm ls

