name: Go

on:
  push:
    branches:
      - "master"
    paths:
      - '**.go'
      - '**.yaml'
      - '**.mod'
  pull_request:
    paths:
      - '**.go'
      - '**.yaml'
      - '**.mod'
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v5
        with:
          go-version: 1.19
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Run test
        run: make test

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2

      - name: Upload coverage report
        uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella